### ISSUE TITLE
Remote API support

### ISSUE THREAD

**Issue by jonesg504** [peter-murray/node-hue-api#125]
Is there support to authenticate with the remote api?

**Comment by peter-murray** [comment]
Not in the existing `v2` API, but I am looking to add this in in the `v3` version that I am currently working on.

**Comment by andertun** [comment]
@peter-murray do you have an eta for `v3`? 😊

**Comment by peter-murray** [comment]
I have been bogged down on dealing with the migration of schedules code from v2 over to v3, am trying to get that completed so that I can provide a drop in shim for the v2 transition to v3.

There are also some quirks that I need to do around the convenience functions for the lights (like setting rgb colors).

Then I need to deal with documentation, so will be about 2 to 3 weeks (maybe a little longer depending on work obligations).

I could cut a alpha release sooner, but not sure if anyone would be interested in that or find it useful.

**Comment by peter-murray** [comment]
There is an `alpha` release `3.0.0-alpha.2` in the npm registry as of now, this will be released as the next major version once I complete the documentation. All the API functionality is practically locked down now for
* lights
* groups
* users
* configuration
* sensors

I am currently also working through the necessary pieces to fully support the remote API

**Comment by andertun** [comment]
Cool - I look forward to check it out 😊

**Comment by glaliberte** [comment]
I am also very interested in Remote API support

**Comment by peter-murray** [comment]
I have just started to look into the necessary changes to support this (as the v3 initial work is done), in theory it is not going to be too difficult, but I need to set up a test application so that I can get the necessary tokens from the remote API so I can develop against it.

I would expect to see something in the next couple of weeks around this.

**Comment by glaliberte** [comment]
The Remote API is very very close to the local API: the calls are all the same with different URL structure and an authorization header in the request. 

Cool to hear that you are working on this.
