### ISSUE TITLE
Fix ts types

### ISSUE THREAD

**Issue by Roaders** [peter-murray/node-hue-api#184]
There are quite a few type definitions that are incomplete or just any. Would you accept Pull Requests to fix this?

**Comment by peter-murray** [comment]
Hi, I am currently doing a lot of refactoring around the definitions and generation of these moving forward.

I have extracted the model into a pure TypeScript library https://github.com/peter-murray/hue-bridge-model that is now being pulled into the `main` branch which will be used to perform a `4.x` version release before I cut a `5.x` version release later this month.

I am happy to accept PRs, but due to the refactoring work, they might already be handled or on my list to sort out. Are you happy to share any areas you have problems with `any` types and I can take a look to ensure these are covered and resolved?

**Comment by Roaders** [comment]
Ok, that sounds great. Thanks.
